"""
Falsification test stubs for claim:
"We are 100% sure we have located the error — i.e. the ABSENCE OF TARGET
COMPRESSION is the SOLE/PRIMARY cause of the 2026-06-04 big_chungus
stepshifter-family constituents scoring cm MSLE worse than their all-zeros
baseline."

Generated by /falsify audit on 2026-06-08.

Verdict: CONTESTED (0 hard, 5 soft falsifications). The core hypothesis
(no-compression is the PRIMARY cause of the per-constituent breakage) survives
as the leading explanation, but the "100% / sole / located" framing is
falsified: alternative contributors were not ruled out and directly-available
evidence (real predictions, actual artifacts) was never inspected.

These tests are TDD RED -- each encodes a verification that must pass before the
diagnosis can honestly be called "located with certainty". Several require real
data / artifacts / the WandB run and cannot run in the bare repo; their
docstrings record what to verify. They double as the dossier pre-flight gaps
(reports/2026-06-08_restore_target_compression_dossier/03_harness_and_invariants.md).

These stubs are marked xfail (not hard-RED) so they document the open verifications
without red-lighting CI on a PR. Remove the marker when the verification is
implemented; an unexpected pass then flags the work as done.
"""

import pytest


@pytest.mark.xfail(reason="falsify P1 — ensemble step un-audited; closes after dossier EXP-01 / register D-20", strict=False)
def test_falsify_01_ensemble_step_adds_no_independent_error():
    """
    Probe 1 (Category H): Was the ensemble/calibration combination ruled out as
    an independent contributor?

    Finding: big_chungus (cm MSLE 2.519) is worse than 17 of its 26 constituents,
    including all 4 DL models (~0.5) and the historical-average baseline (0.581).
    The combination/calibration step was never examined.
    Severity: soft

    Expected: with the constituents' predictions fixed, the ensemble's MSLE is
    explained purely by the combination rule (no independent error introduced by
    the calibration step). Verify by reconstructing the ensemble prediction from
    the constituents and comparing to the reported 2.519.
    """
    # TODO: load constituent predictions for the big_chungus run; reconstruct the
    # ensemble per its actual combination/calibration rule; confirm 2.519 is
    # reproduced without an extra error term from the ensemble step.
    assert False, "Ensemble/calibration step never examined; 'sole cause' unverified."


@pytest.mark.xfail(reason="falsify P2 — Hurdle two-stage not reproduced; closes after dossier EXP-01", strict=False)
def test_falsify_02_reproduction_covers_hurdle_two_stage():
    """
    Probe 2 (Category A): Does the reproduction model the HurdleModel two-stage
    structure that makes up a large share of the broken cohort?

    Finding: the synthetic repro used a flat sklearn regressor. Many broken
    constituents are HurdleModels, whose binary stage (x>0) is unaffected by
    target compression -- a structure the proxy does not model.
    Severity: soft

    Expected: a raw-vs-log1p reproduction using the actual HurdleModel (binary +
    positive stages) on representative data shows the same raw>worse-than-zeros
    signature, OR the diagnosis is refined to state which families it covers.
    """
    # TODO: run raw vs log1p on a real HurdleModel (not a flat regressor),
    # scored cm MSLE vs the all-zeros baseline.
    assert False, "Reproduction proxy does not cover HurdleModel two-stage structure."


@pytest.mark.xfail(reason="falsify P3 — real predictions never inspected; closes after dossier EXP-01", strict=False)
def test_falsify_03_real_predictions_overpredict_on_true_zeros():
    """
    Probe 3 (Category H): Is the over-prediction claim grounded in the ACTUAL
    broken predictions, not just aggregate MSLE + a synthetic proxy?

    Finding: the actual predictions were never inspected, even though the
    calibration reports contain a 'Prediction Samples' section (Sequence 0/6/12).
    Severity: soft

    Expected: for >=1 real broken constituent, mean predicted value on true-zero
    country-months is materially > 0 (the over-prediction signature), measured on
    the actual prediction output, not the synthetic proxy.
    """
    # TODO: extract actual constituent predictions (report 'Prediction Samples' or
    # the prediction parquet); on true-zero cells, assert mean prediction >> 0.
    assert False, "Real broken predictions never inspected; over-prediction inferred only."


@pytest.mark.xfail(reason="falsify P5 — identical-metrics mislink unverified; register D-21", strict=False)
def test_falsify_05_identical_metrics_anomaly_explained():
    """
    Probe 5 (Category H): Does the 'no compression' theory explain ALL anomalies
    in the broken cohort?

    Finding: plastic_beach and brown_cheese returned byte-identical metrics
    (RMSLE 2.048527, MSE 51521.055532, MSLE 4.196935, y_hat 43.696734) despite
    confirmed-different configs/querysets (aquastat vs baseline) -- a data/artifact
    mislink that 'no compression' does not explain. A second defect exists.
    Severity: soft

    Expected: either the identical metrics are explained (and benign), or the
    second defect (artifact/prediction-file mislink) is acknowledged as a distinct
    error -- in which case 'we located THE error' (singular) is false.
    """
    # TODO: confirm whether plastic_beach and brown_cheese share a prediction file
    # / artifact id in the run; explain or register the mislink as a separate error.
    assert False, "Byte-identical metrics from different models = unexplained second defect."


@pytest.mark.xfail(reason="falsify P6 — actual artifacts never verified; register D-17/D-21", strict=False)
def test_falsify_06_constituent_artifacts_verified_raw_trained():
    """
    Probe 6 (Category A): Were the ACTUAL big_chungus constituents verified to be
    raw-trained, not log-trained-then-predicted-raw (the mismatch alternative)?

    Finding: no constituent artifact was inspected (only cheap_thrills, not in the
    ensemble); WandB run 2689xjtl was absent. The 'raw-trained' conclusion is
    indirect.
    Severity: soft

    Expected: >=1 actual big_chungus constituent artifact (via WandB 2689xjtl or
    the stored pkl) is confirmed trained AFTER the 08ee2eb revert (2026-04-11) in
    raw space -- directly, not by absence-of-counterexample.
    """
    # TODO: fetch the WandB 2689xjtl artifacts (or the run's stored pkls); confirm
    # training timestamp post-revert and that no internal log transform was active.
    assert False, "Actual constituent artifacts never inspected; mismatch dismissed indirectly."
