"""
Falsification audit stubs for PR #51 (ADR-002 timestamp contract).
Generated by falsification audit 2026-05-19.

These tests encode the invariant that was soft-falsified:
the PR as pushed must match the reviewed working-tree state.
"""

import subprocess


def test_no_uncommitted_changes_on_pr_branch():
    """
    SOFT FALSIFICATION — P5: Uncommitted state drift.

    The review applied three fixes (Deciders field, removed boilerplate,
    added GitHub links) that were not committed or pushed. The PR on
    GitHub therefore shows stale content that differs from the reviewed
    working-tree state.

    This test fails if there are uncommitted changes to docs/ADRs/ on
    the current branch, catching the case where review edits are applied
    locally but not pushed.
    """
    result = subprocess.run(
        ["git", "diff", "--name-only", "--", "docs/ADRs/"],
        capture_output=True,
        text=True,
    )
    changed_files = result.stdout.strip()
    assert changed_files == "", (
        f"Uncommitted changes in docs/ADRs/: {changed_files}. "
        "Review edits must be committed and pushed before merge."
    )
